
pipeline {
    agent {
       label 'slave2'   
    }
         
    
     parameters{
        string(name: 'HOSTNAME' , defaultValue: '192.168.56.1', description: ' The hostname')
        string(name: 'PATH1' , defaultValue: 'C:/WINDOWS' , description: 'The directory path')
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'javac Client/Client.java'
            }
        }
        stage('Run') {
            steps {
              sh """
              cd Client
              java Client ${HOSTNAME} ${PATH1}
              """
            }
        }
    }
}
