pipeline {
    agent {
       label 'slave1'   
    }

    stages {
        stage('directory') {
            steps {
                echo 'Building..'
                sh """ls"""
            }
        }
        
        stage('Build') {
            steps {
                sh "chmod +x -R ${env.WORKSPACE}"
                sh """
                  ./Server.java
                """
            }
        }
        stage('Run') {
            steps {
              sh """
              cd Server
              java Server ${HOSTNAME} ${PATH1}
              """
            }
        }
    
  
  } 
}
