pipeline {
    agent {
       label 'slave'   
    }

    stages {
        stage('directory') {
            steps {
                echo 'Building..'
                sh """ls"""
            }
        }
          stage('build') {
            steps {
              script{
               
                sh """ 
                cd Server
                ls
                javac Server.java
                """
              }
            }
        }
        stage('Run') {
            steps {
              sh """
              cd Server
              java Server
              """
            }
        }
        
    
    
  
  } 
}
