pipeline {
    agent {
       label 'slave'   
    }

    stages {
        stage('directory') {
            steps {
                echo 'Building..'
                sh """ls"""
            }
        }
          stage('build') {
            steps {
                sh "chmod a+rx ./Server/Server.java";
                sh "./Server/Server.java"
            }
        }
        stage('Run') {
            steps {
              sh """
              cd Server
              java Server
              """
            }
        }
        
    
    
  
  } 
}
